CREATE INDEX `idx_listings_region` ON `listings` (`regionId`);--> statement-breakpoint
CREATE INDEX `idx_listings_seller` ON `listings` (`sellerId`);--> statement-breakpoint
CREATE INDEX `idx_listings_active_last_seen` ON `listings` (`isActive`,`lastSeenAt`);--> statement-breakpoint
CREATE INDEX `idx_listings_active_region_last_seen` ON `listings` (`isActive`,`regionId`,`lastSeenAt`);--> statement-breakpoint
CREATE INDEX `idx_listings_platform_listing` ON `listings` (`platformListingId`);--> statement-breakpoint
CREATE INDEX `idx_listings_price` ON `listings` (`price`);--> statement-breakpoint
CREATE INDEX `idx_listings_area` ON `listings` (`area`);--> statement-breakpoint
CREATE INDEX `idx_listings_rooms` ON `listings` (`rooms`);--> statement-breakpoint
CREATE INDEX `idx_listings_platform` ON `listings` (`platform`);--> statement-breakpoint
CREATE INDEX `idx_listings_district` ON `listings` (`district`);--> statement-breakpoint
CREATE INDEX `idx_listings_state` ON `listings` (`state`);--> statement-breakpoint
CREATE INDEX `idx_price_history_listing` ON `price_history` (`listingId`);--> statement-breakpoint
CREATE INDEX `idx_regions_type_name` ON `regions` (`type`,`name`);--> statement-breakpoint
CREATE INDEX `idx_regions_parent_type` ON `regions` (`parentId`,`type`);--> statement-breakpoint
CREATE INDEX `idx_regions_name` ON `regions` (`name`);--> statement-breakpoint
CREATE INDEX `idx_scrape_runs_type` ON `scrape_runs` (`type`);--> statement-breakpoint
CREATE INDEX `idx_scrape_runs_status` ON `scrape_runs` (`status`);--> statement-breakpoint
CREATE INDEX `idx_scrape_runs_started_at` ON `scrape_runs` (`startedAt`);--> statement-breakpoint
CREATE INDEX `idx_scrape_runs_type_started_at` ON `scrape_runs` (`type`,`startedAt`);--> statement-breakpoint
CREATE INDEX `idx_seller_history_seller` ON `seller_history` (`sellerId`);--> statement-breakpoint
CREATE INDEX `idx_sellers_platform` ON `sellers` (`platform`);--> statement-breakpoint
CREATE INDEX `idx_sellers_active_ads` ON `sellers` (`activeAdCount`);--> statement-breakpoint
CREATE INDEX `idx_sellers_name` ON `sellers` (`name`);--> statement-breakpoint
CREATE UNIQUE INDEX `uniq_sellers_platform_platformSeller` ON `sellers` (`platform`,`platformSellerId`);